export const REPORT_CATEGORIES = [
  { id: 'all', title: 'All Reports', icon: 'FileSpreadsheet' },
  { id: 'students', title: 'Student Reports', icon: 'Users' },
  { id: 'academic', title: 'Academic Reports', icon: 'GraduationCap' },
  { id: 'fees', title: 'Fee Reports', icon: 'CreditCard' },
  { id: 'staff', title: 'Staff Reports', icon: 'Briefcase' },
  { id: 'payroll', title: 'Payroll Reports', icon: 'Calculator' },
  { id: 'finance', title: 'Finance Reports', icon: 'Wallet' },
  { id: 'audit', title: 'Audit Reports', icon: 'ShieldCheck' },
];

export const REPORT_REGISTRY = [
  // --- Student Reports ---
  {
    id: 'student-directory',
    category: 'students',
    title: 'Student Directory',
    description: 'Comprehensive list of enrolled students with admission details, guardian contact, and status.',
    endpoint: '/reports/students/directory',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'classId', 'sectionId', 'mediumId', 'streamId', 'status', 'search'],
    columns: [
      { key: 'admissionNo', label: 'Admission No', bold: true },
      { key: 'studentName', label: 'Student Name' },
      { key: 'guardianName', label: 'Guardian' },
      { key: 'phone', label: 'Phone' },
      { key: 'className', label: 'Class' },
      { key: 'sectionName', label: 'Section' },
      { key: 'mediumName', label: 'Medium' },
      { key: 'streamName', label: 'Stream' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  {
    id: 'class-wise-students',
    category: 'students',
    title: 'Class-wise Student List',
    description: 'Student directory organized and grouped by Class.',
    endpoint: '/reports/students/class-wise',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'classId', 'mediumId', 'streamId'],
    isGrouped: true,
    groupedKey: 'students',
    columns: [
      { key: 'sNo', label: 'S.No' },
      { key: 'admissionNo', label: 'Admission No' },
      { key: 'studentName', label: 'Student Name' },
      { key: 'guardianName', label: 'Guardian' },
      { key: 'phone', label: 'Phone' },
      { key: 'sectionName', label: 'Section' },
    ],
  },
  {
    id: 'section-wise-students',
    category: 'students',
    title: 'Section-wise Student List',
    description: 'Students grouped by Class and Section.',
    endpoint: '/reports/students/section-wise',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'classId', 'sectionId'],
    isGrouped: true,
    groupedKey: 'students',
    columns: [
      { key: 'admissionNo', label: 'Admission No' },
      { key: 'studentName', label: 'Student Name' },
      { key: 'guardianName', label: 'Guardian' },
      { key: 'phone', label: 'Phone' },
    ],
  },
  {
    id: 'medium-wise-students',
    category: 'students',
    title: 'Medium-wise Student List',
    description: 'Distribution and total counts of students enrolled by Medium of instruction.',
    endpoint: '/reports/students/medium-wise',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'mediumId'],
    columns: [
      { key: 'mediumName', label: 'Medium', bold: true },
      { key: 'studentCount', label: 'Total Enrolled Students', align: 'right' },
    ],
  },
  {
    id: 'stream-wise-students',
    category: 'students',
    title: 'Stream-wise Student List',
    description: 'Student breakdown by Academic Stream (Science, Arts, Commerce).',
    endpoint: '/reports/students/stream-wise',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'streamId'],
    columns: [
      { key: 'streamName', label: 'Stream', bold: true },
      { key: 'studentCount', label: 'Total Enrolled Students', align: 'right' },
    ],
  },
  {
    id: 'student-status',
    category: 'students',
    title: 'Student Status Breakdown',
    description: 'Counts of active, graduated, left, and archived students.',
    endpoint: '/reports/students/status',
    pdfTemplate: 'genericReport',
    filters: [],
    columns: [
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'count', label: 'Total Count', align: 'right' },
    ],
  },

  // --- Academic Reports ---
  {
    id: 'class-strength',
    category: 'academic',
    title: 'Class Strength Report',
    description: 'Enrollment capacity and current student strength across all classes.',
    endpoint: '/reports/academic/class-strength',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId'],
    columns: [
      { key: 'className', label: 'Class Name', bold: true },
      { key: 'code', label: 'Class Code' },
      { key: 'studentCount', label: 'Active Enrolled Students', align: 'right' },
    ],
  },
  {
    id: 'academic-enrollment',
    category: 'academic',
    title: 'Academic Year Enrollment Report',
    description: 'Summary of active, promoted, repeated, and left enrollments.',
    endpoint: '/reports/academic/enrollment',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId'],
    columns: [
      { key: 'status', label: 'Enrollment Status', type: 'badge' },
      { key: 'count', label: 'Student Count', align: 'right' },
    ],
  },

  // --- Fee Reports ---
  {
    id: 'fee-collection',
    category: 'fees',
    title: 'Fee Collection Report',
    description: 'Itemized record of fee payments collected with payment modes and receipt numbers.',
    endpoint: '/reports/fees/collection',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'startDate', 'endDate', 'classId', 'feeTypeId', 'paymentMode'],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'receiptNo', label: 'Receipt No', bold: true },
      { key: 'studentName', label: 'Student' },
      { key: 'admissionNo', label: 'Admission No' },
      { key: 'className', label: 'Class' },
      { key: 'feeType', label: 'Fee Type' },
      { key: 'amount', label: 'Amount (₹)', type: 'currency', align: 'right' },
      { key: 'paymentMode', label: 'Payment Mode', type: 'badge' },
    ],
  },
  {
    id: 'fee-outstanding',
    category: 'fees',
    title: 'Outstanding Fee Report',
    description: 'List of students with pending balances, total charged, paid, and remaining dues.',
    endpoint: '/reports/fees/outstanding',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'classId', 'sectionId', 'mediumId', 'streamId', 'status'],
    columns: [
      { key: 'admissionNo', label: 'Admission No' },
      { key: 'studentName', label: 'Student Name', bold: true },
      { key: 'phone', label: 'Phone' },
      { key: 'className', label: 'Class' },
      { key: 'totalCharged', label: 'Total Charged', type: 'currency', align: 'right' },
      { key: 'paidAmount', label: 'Total Paid', type: 'currency', align: 'right' },
      { key: 'balance', label: 'Outstanding Dues (₹)', type: 'currency', align: 'right', highlight: true },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  {
    id: 'student-fee-ledger',
    category: 'fees',
    title: 'Student Fee Ledger',
    description: 'Chronological charge and payment statement for an individual student.',
    endpoint: '/reports/fees/student-ledger',
    pdfTemplate: 'genericReport',
    filters: ['studentId', 'academicYearId'],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'description', label: 'Transaction Description' },
      { key: 'refNo', label: 'Ref / Receipt #' },
      { key: 'chargeAmount', label: 'Charge (₹)', type: 'currency', align: 'right' },
      { key: 'paymentAmount', label: 'Payment (₹)', type: 'currency', align: 'right' },
      { key: 'balance', label: 'Running Balance (₹)', type: 'currency', align: 'right', bold: true },
    ],
  },
  {
    id: 'class-fee-collection',
    category: 'fees',
    title: 'Class-wise Fee Collection',
    description: 'Class-by-class comparison of total collection versus pending dues.',
    endpoint: '/reports/fees/class-collection',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId'],
    columns: [
      { key: 'className', label: 'Class Name', bold: true },
      { key: 'studentCount', label: 'Student Count', align: 'right' },
      { key: 'collection', label: 'Total Collected (₹)', type: 'currency', align: 'right' },
      { key: 'outstanding', label: 'Total Outstanding Dues (₹)', type: 'currency', align: 'right', highlight: true },
    ],
  },
  {
    id: 'fee-batches',
    category: 'fees',
    title: 'Fee Generation Report',
    description: 'Audit history of recurring fee generation runs and total amounts generated.',
    endpoint: '/reports/fees/batches',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId'],
    columns: [
      { key: 'date', label: 'Date Generated', type: 'date' },
      { key: 'month', label: 'Month' },
      { key: 'targetClass', label: 'Target Class' },
      { key: 'generatedCount', label: 'Generated Count', align: 'right' },
      { key: 'skippedCount', label: 'Skipped Count', align: 'right' },
      { key: 'totalAmount', label: 'Total Amount (₹)', type: 'currency', align: 'right' },
      { key: 'generatedBy', label: 'Generated By' },
    ],
  },



  // --- Staff Reports ---
  {
    id: 'staff-directory',
    category: 'staff',
    title: 'Staff Directory',
    description: 'Master record of employee profiles, departments, designations, and employment status.',
    endpoint: '/reports/staff/directory',
    pdfTemplate: 'genericReport',
    filters: ['department', 'designation', 'role', 'status'],
    columns: [
      { key: 'employeeId', label: 'Emp ID', bold: true },
      { key: 'name', label: 'Staff Name' },
      { key: 'department', label: 'Department' },
      { key: 'designation', label: 'Designation' },
      { key: 'role', label: 'Role' },
      { key: 'phone', label: 'Phone' },
      { key: 'joiningDate', label: 'Joining Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  {
    id: 'department-wise-staff',
    category: 'staff',
    title: 'Department-wise Staff Report',
    description: 'Employees grouped by operational school department.',
    endpoint: '/reports/staff/department-wise',
    pdfTemplate: 'genericReport',
    filters: ['status'],
    isGrouped: true,
    groupedKey: 'staff',
    columns: [
      { key: 'employeeId', label: 'Emp ID' },
      { key: 'name', label: 'Staff Name' },
      { key: 'designation', label: 'Designation' },
      { key: 'joiningDate', label: 'Joining Date', type: 'date' },
    ],
  },
  {
    id: 'designation-wise-staff',
    category: 'staff',
    title: 'Designation-wise Staff Report',
    description: 'Staff members organized by professional job designation.',
    endpoint: '/reports/staff/designation-wise',
    pdfTemplate: 'genericReport',
    filters: ['status'],
    isGrouped: true,
    groupedKey: 'staff',
    columns: [
      { key: 'employeeId', label: 'Emp ID' },
      { key: 'name', label: 'Staff Name' },
      { key: 'department', label: 'Department' },
    ],
  },
  {
    id: 'staff-status',
    category: 'staff',
    title: 'Staff Status Report',
    description: 'Summary counts of active, inactive, resigned, and on-leave staff.',
    endpoint: '/reports/staff/status',
    pdfTemplate: 'genericReport',
    filters: [],
    columns: [
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'count', label: 'Staff Count', align: 'right' },
    ],
  },

  // --- Payroll Reports ---
  {
    id: 'monthly-salary',
    category: 'payroll',
    title: 'Monthly Salary Report',
    description: 'Payroll snapshot by month including working days, deductions, bonuses, and net pay.',
    endpoint: '/reports/payroll/monthly',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'month', 'year', 'department', 'designation', 'status'],
    columns: [
      { key: 'employeeId', label: 'Emp ID' },
      { key: 'staffName', label: 'Staff Name', bold: true },
      { key: 'department', label: 'Dept' },
      { key: 'month', label: 'Month' },
      { key: 'workedDays', label: 'Days Worked', align: 'right' },
      { key: 'baseSalary', label: 'Base Pay (₹)', type: 'currency', align: 'right' },
      { key: 'bonus', label: 'Bonus (₹)', type: 'currency', align: 'right' },
      { key: 'advanceDeduction', label: 'Adv Deduct (₹)', type: 'currency', align: 'right' },
      { key: 'netSalary', label: 'Net Salary (₹)', type: 'currency', align: 'right', bold: true },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  {
    id: 'salary-payments',
    category: 'payroll',
    title: 'Salary Payment Vouchers',
    description: 'Historical records of disbursed salary payment vouchers and payment modes.',
    endpoint: '/reports/payroll/payments',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'startDate', 'endDate', 'paymentMode', 'staffId'],
    columns: [
      { key: 'paymentDate', label: 'Payment Date', type: 'date' },
      { key: 'paymentNumber', label: 'Voucher #', bold: true },
      { key: 'staffName', label: 'Staff Name' },
      { key: 'employeeId', label: 'Emp ID' },
      { key: 'months', label: 'Paid Months' },
      { key: 'netSalary', label: 'Disbursed (₹)', type: 'currency', align: 'right' },
      { key: 'paymentMode', label: 'Payment Mode', type: 'badge' },
    ],
  },
  {
    id: 'staff-salary-ledger',
    category: 'payroll',
    title: 'Staff Salary Ledger',
    description: 'Individual staff salary accrual and disbursement timeline.',
    endpoint: '/reports/payroll/staff-ledger',
    pdfTemplate: 'genericReport',
    filters: ['staffId', 'academicYearId'],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'description', label: 'Description' },
      { key: 'refNo', label: 'Voucher #' },
      { key: 'salaryAmount', label: 'Salary Accrued (₹)', type: 'currency', align: 'right' },
      { key: 'paymentAmount', label: 'Disbursed (₹)', type: 'currency', align: 'right' },
      { key: 'balance', label: 'Pending Balance (₹)', type: 'currency', align: 'right', bold: true },
    ],
  },
  {
    id: 'pending-salary',
    category: 'payroll',
    title: 'Pending Salary Dues Report',
    description: 'Unpaid and partially paid monthly salary records.',
    endpoint: '/reports/payroll/pending',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'month', 'department', 'status'],
    columns: [
      { key: 'employeeId', label: 'Emp ID' },
      { key: 'staffName', label: 'Staff Name', bold: true },
      { key: 'department', label: 'Department' },
      { key: 'month', label: 'Month' },
      { key: 'netSalary', label: 'Net Salary (₹)', type: 'currency', align: 'right' },
      { key: 'paidAmount', label: 'Paid (₹)', type: 'currency', align: 'right' },
      { key: 'balance', label: 'Pending Dues (₹)', type: 'currency', align: 'right', highlight: true },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  {
    id: 'staff-advances',
    category: 'payroll',
    title: 'Staff Advance & Recovery Report',
    description: 'Track staff salary advances issued, amounts allocated in payroll, recoveries completed, and available balances.',
    endpoint: '/reports/payroll/advances',
    pdfTemplate: 'genericReport',
    filters: ['startDate', 'endDate', 'transactionType', 'status'],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'type', label: 'Type', type: 'badge' },
      { key: 'staffName', label: 'Staff Name', bold: true },
      { key: 'employeeId', label: 'Emp ID' },
      { key: 'reference', label: 'Reference / Voucher' },
      { key: 'payrollPeriod', label: 'Payroll Period' },
      { key: 'disbursed', label: 'Disbursed (₹)', type: 'currency', align: 'right' },
      { key: 'recovered', label: 'Recovered (₹)', type: 'currency', align: 'right' },
      { key: 'balance', label: 'Advance Balance (₹)', type: 'currency', align: 'right', bold: true },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  {
    id: 'individual-staff-advance',
    category: 'payroll',
    title: 'Individual Staff Advance Statement',
    description: 'Chronological advance disbursement and payroll recovery ledger for an individual staff member.',
    endpoint: '/reports/payroll/individual-advance',
    pdfTemplate: 'genericReport',
    filters: ['staffId', 'startDate', 'endDate'],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'type', label: 'Type', type: 'badge' },
      { key: 'description', label: 'Description', bold: true },
      { key: 'refNo', label: 'Ref / Voucher #' },
      { key: 'disbursedAmount', label: 'Disbursed (₹)', type: 'currency', align: 'right' },
      { key: 'recoveredAmount', label: 'Recovered (₹)', type: 'currency', align: 'right' },
      { key: 'balance', label: 'Advance Balance (₹)', type: 'currency', align: 'right', bold: true },
    ],
  },


  // --- Finance Reports ---
  {
    id: 'financial-summary',
    category: 'finance',
    title: 'Financial Summary Report',
    description: 'High-level financial overview showing Total Credits, Total Debits, and Net Cash Movement.',
    endpoint: '/reports/finance/summary',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'startDate', 'endDate'],
    isCustomLayout: 'financialSummary',
    columns: [],
  },
  {
    id: 'financial-transactions',
    category: 'finance',
    title: 'Financial Ledger Transaction Report',
    description: 'Itemized double-entry transaction ledger of all credits and debits across school operations.',
    endpoint: '/reports/finance/transactions',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'startDate', 'endDate', 'type', 'sourceType', 'paymentMode'],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'description', label: 'Description' },
      { key: 'sourceType', label: 'Source' },
      { key: 'type', label: 'Type (Credit/Debit)', type: 'badge' },
      { key: 'paymentMode', label: 'Payment Mode' },
      { key: 'referenceNumber', label: 'Ref #' },
      { key: 'amount', label: 'Amount (₹)', type: 'currency', align: 'right', bold: true },
    ],
  },
  {
    id: 'expense-report',
    category: 'finance',
    title: 'School Expenditure Report',
    description: 'Itemized operational school expenses grouped by category and payment mode.',
    endpoint: '/reports/finance/expenses',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'startDate', 'endDate', 'categoryId', 'paymentMode'],
    columns: [
      { key: 'date', label: 'Expense Date', type: 'date' },
      { key: 'category', label: 'Category', bold: true },
      { key: 'description', label: 'Description / Purpose' },
      { key: 'paymentMode', label: 'Payment Mode' },
      { key: 'referenceNo', label: 'Ref #' },
      { key: 'amount', label: 'Amount (₹)', type: 'currency', align: 'right', highlight: true },
    ],
  },
  {
    id: 'fund-report',
    category: 'finance',
    title: 'Fund Addition Report',
    description: 'Records of external capital contributions and funds injected into the school.',
    endpoint: '/reports/finance/funds',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'startDate', 'endDate', 'fundSourceId', 'paymentMode'],
    columns: [
      { key: 'date', label: 'Date Added', type: 'date' },
      { key: 'fundSource', label: 'Fund Source', bold: true },
      { key: 'paymentMode', label: 'Payment Mode' },
      { key: 'referenceNumber', label: 'Ref #' },
      { key: 'remarks', label: 'Remarks' },
      { key: 'amount', label: 'Fund Contribution (₹)', type: 'currency', align: 'right' },
    ],
  },
  {
    id: 'payment-modes-summary',
    category: 'finance',
    title: 'Payment Mode Analysis',
    description: 'Movement of money across Cash, Bank, UPI, Cheque, and Demand Draft.',
    endpoint: '/reports/finance/payment-modes',
    pdfTemplate: 'genericReport',
    filters: ['academicYearId', 'startDate', 'endDate'],
    isCustomLayout: 'paymentModes',
    columns: [],
  },

  // --- Audit Reports ---
  {
    id: 'audit-logs',
    category: 'audit',
    title: 'System Audit Logs',
    description: 'Audit trail of administrative actions, report generations, and system events.',
    endpoint: '/reports/audit/logs',
    pdfTemplate: 'genericReport',
    filters: ['startDate', 'endDate', 'action', 'entityType'],
    columns: [
      { key: 'date', label: 'Timestamp', type: 'date' },
      { key: 'userName', label: 'User', bold: true },
      { key: 'action', label: 'Action', type: 'badge' },
      { key: 'module', label: 'Module / Entity' },
      { key: 'details', label: 'Details Snapshot' },
    ],
  },
];

export const getReportById = (id) => REPORT_REGISTRY.find((r) => r.id === id);
