import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { History, Eye } from 'lucide-react';
import { feeService } from '../../services/fee.service.js';
import { useAcademicYear } from '../../hooks/useAcademicYear.js';
import { Badge } from '../../components/ui/Badge.jsx';
import { Modal } from '../../components/ui/Modal.jsx';
import { Skeleton } from '../../components/ui/Skeleton.jsx';
import { EmptyState } from '../../components/ui/EmptyState.jsx';
import { Pagination } from '../../components/ui/Pagination.jsx';
import { toast } from '../../components/ui/Toast.jsx';

export const GeneratedHistoryPage = () => {
  const navigate = useNavigate();
  const { selectedYearId } = useAcademicYear();

  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [pagination, setPagination] = useState({ page: 1, totalPages: 1, total: 0 });

  // Detail Modal State
  const [selectedBatch, setSelectedBatch] = useState(null);
  const [batchDetailLoading, setBatchDetailLoading] = useState(false);
  const [isDetailModalOpen, setIsDetailModalOpen] = useState(false);

  const fetchHistory = async (page = 1) => {
    setLoading(true);
    try {
      const res = await feeService.getGenerationHistory({
        academicYearId: selectedYearId,
        page,
        limit: 15,
      });
      setHistory(res.data || []);
      setPagination(res.pagination || { page: 1, totalPages: 1, total: 0 });
    } catch {
      toast.error('Failed to load generation history');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchHistory(1);
  }, [selectedYearId]);

  const handleOpenDetailModal = async (batchId) => {
    setIsDetailModalOpen(true);
    setBatchDetailLoading(true);
    try {
      const res = await feeService.getGenerationBatchDetails(batchId);
      setSelectedBatch(res.data);
    } catch {
      toast.error('Failed to load batch details');
      setIsDetailModalOpen(false);
    } finally {
      setBatchDetailLoading(false);
    }
  };

  const getModeBadge = (mode) => {
    switch (mode) {
      case 'ENTIRE_SCHOOL':
        return <Badge variant="indigo" size="sm">Entire School</Badge>;
      case 'BY_CLASS':
        return <Badge variant="info" size="sm">By Class</Badge>;
      case 'BY_STUDENT':
        return <Badge variant="warning" size="sm">By Student</Badge>;
      default:
        return <Badge variant="neutral" size="sm">{mode}</Badge>;
    }
  };

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-2xl border border-slate-200 shadow-2xs overflow-hidden">
        <div className="p-4 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <History className="w-4 h-4 text-slate-500" />
            <h3 className="text-sm font-bold text-slate-900">Generated Fee History</h3>
          </div>
          <span className="text-xs text-slate-500 font-mono">Total Runs: {pagination.total}</span>
        </div>

        {loading ? (
          <div className="p-6 space-y-4">
            <Skeleton className="h-10 w-full" />
            <Skeleton className="h-12 w-full" />
            <Skeleton className="h-12 w-full" />
            <Skeleton className="h-12 w-full" />
          </div>
        ) : history.length === 0 ? (
          <EmptyState
            icon={History}
            title="No Fee Generation history yet."
            description="Generate fees to begin."
            actionLabel="Generate Fees"
            onAction={() => navigate('/app/fees/generate')}
          />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-50 border-b border-slate-200 text-slate-500 font-bold uppercase text-[10px]">
                <tr>
                  <th className="px-4 py-3">Month</th>
                  <th className="px-4 py-3">Academic Year</th>
                  <th className="px-4 py-3">Mode</th>
                  <th className="px-4 py-3">Target Info</th>
                  <th className="px-4 py-3">Generated By</th>
                  <th className="px-4 py-3">Date & Time</th>
                  <th className="px-4 py-3 text-right">Created Charges</th>
                  <th className="px-4 py-3 text-right">Total Amount</th>
                  <th className="px-4 py-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {history.map((batch) => (
                  <tr key={batch.id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="px-4 py-3 font-bold text-slate-900">{batch.month}</td>
                    <td className="px-4 py-3 text-slate-600 font-semibold">{batch.academicYear?.name}</td>
                    <td className="px-4 py-3">{getModeBadge(batch.mode)}</td>
                    <td className="px-4 py-3 text-slate-700">
                      {batch.class
                        ? `${batch.class.name} (${batch.medium?.name || ''})`
                        : batch.student
                        ? `${batch.student.name} (${batch.student.admissionNo})`
                        : 'All Classes'}
                    </td>
                    <td className="px-4 py-3 text-slate-600">
                      {batch.createdBy?.name || 'School Admin'}
                    </td>
                    <td className="px-4 py-3 text-slate-500 font-mono text-[11px]">
                      {new Date(batch.createdAt).toLocaleString('en-IN', {
                        dateStyle: 'medium',
                        timeStyle: 'short',
                      })}
                    </td>
                    <td className="px-4 py-3 text-right font-mono font-bold text-indigo-600">
                      {batch.generatedCount}
                    </td>
                    <td className="px-4 py-3 text-right font-mono font-extrabold text-slate-900">
                      ₹{Number(batch.totalAmount).toLocaleString('en-IN')}
                    </td>
                    <td className="px-4 py-3 text-right">
                      <button
                        onClick={() => handleOpenDetailModal(batch.id)}
                        className="inline-flex items-center gap-1 px-2.5 py-1 text-[11px] font-semibold text-indigo-600 bg-indigo-50 hover:bg-indigo-100 rounded-md transition-colors"
                      >
                        <Eye className="w-3.5 h-3.5" /> Details
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {pagination.totalPages > 1 && (
          <div className="p-4 border-t border-slate-100">
            <Pagination
              currentPage={pagination.page}
              totalPages={pagination.totalPages}
              onPageChange={(p) => fetchHistory(p)}
            />
          </div>
        )}
      </div>

      {/* Batch Details Modal */}
      <Modal
        isOpen={isDetailModalOpen}
        onClose={() => setIsDetailModalOpen(false)}
        title="Fee Generation Batch Details"
        size="lg"
      >
        {batchDetailLoading ? (
          <div className="p-6 space-y-3">
            <Skeleton className="h-10 w-full" />
            <Skeleton className="h-24 w-full" />
            <Skeleton className="h-40 w-full" />
          </div>
        ) : selectedBatch ? (
          <div className="space-y-5">
            {/* Metadata Summary Card */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50 p-4 rounded-xl border border-slate-200 text-xs">
              <div>
                <span className="text-[10px] font-bold text-slate-400 block uppercase">Month</span>
                <span className="font-bold text-slate-900">{selectedBatch.month}</span>
              </div>
              <div>
                <span className="text-[10px] font-bold text-slate-400 block uppercase">Generation Mode</span>
                <span>{getModeBadge(selectedBatch.mode)}</span>
              </div>
              <div>
                <span className="text-[10px] font-bold text-slate-400 block uppercase">Generated Count</span>
                <span className="font-mono font-bold text-indigo-600">{selectedBatch.generatedCount}</span>
              </div>
              <div>
                <span className="text-[10px] font-bold text-slate-400 block uppercase">Total Amount</span>
                <span className="font-mono font-extrabold text-emerald-600">
                  ₹{Number(selectedBatch.totalAmount).toLocaleString('en-IN')}
                </span>
              </div>
            </div>

            {/* Skipped Details List */}
            {selectedBatch.details?.skippedStudents?.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider">
                  Skipped Charges Log ({selectedBatch.details.skippedStudents.length})
                </h4>
                <div className="border border-slate-200 rounded-xl overflow-hidden max-h-48 overflow-y-auto">
                  <table className="w-full text-left text-xs">
                    <thead className="bg-slate-100 text-slate-500 font-bold text-[10px] uppercase">
                      <tr>
                        <th className="px-3 py-2">Admission No</th>
                        <th className="px-3 py-2">Student Name</th>
                        <th className="px-3 py-2">Reason</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {selectedBatch.details.skippedStudents.map((item, idx) => (
                        <tr key={idx} className="hover:bg-slate-50">
                          <td className="px-3 py-1.5 font-mono text-slate-600">{item.admissionNo}</td>
                          <td className="px-3 py-1.5 font-semibold text-slate-900">{item.studentName}</td>
                          <td className="px-3 py-1.5 text-rose-600 font-semibold">{item.reason}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Charges Sample Preview */}
            <div className="space-y-2">
              <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider">
                Generated Charges ({selectedBatch.charges?.length || 0})
              </h4>
              <div className="border border-slate-200 rounded-xl overflow-hidden max-h-56 overflow-y-auto">
                <table className="w-full text-left text-xs">
                  <thead className="bg-slate-100 text-slate-500 font-bold text-[10px] uppercase">
                    <tr>
                      <th className="px-3 py-2">Student</th>
                      <th className="px-3 py-2">Fee Head</th>
                      <th className="px-3 py-2 text-right">Amount</th>
                      <th className="px-3 py-2 text-right">Status</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {(selectedBatch.charges || []).map((ch) => (
                      <tr key={ch.id} className="hover:bg-slate-50">
                        <td className="px-3 py-1.5 font-semibold text-slate-900">
                          {ch.student?.name} <span className="text-slate-400 font-mono">({ch.student?.admissionNo})</span>
                        </td>
                        <td className="px-3 py-1.5 text-slate-700">{ch.title}</td>
                        <td className="px-3 py-1.5 text-right font-mono font-bold text-slate-900">
                          ₹{Number(ch.amount).toLocaleString('en-IN')}
                        </td>
                        <td className="px-3 py-1.5 text-right">
                          <Badge variant="warning" size="sm">{ch.status}</Badge>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            <div className="flex justify-end pt-3 border-t border-slate-100">
              <button
                onClick={() => setIsDetailModalOpen(false)}
                className="px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100 rounded-lg"
              >
                Close
              </button>
            </div>
          </div>
        ) : null}
      </Modal>
    </div>
  );
};
